# Generated by Django 4.0.5 on 2022-06-23 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easyreport_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteRegistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('clienteCnpj', models.CharField(max_length=20, unique=True)),
                ('clienteNome', models.CharField(max_length=50)),
                ('clienteRazaoSocial', models.CharField(max_length=50)),
                ('clienteEnderecoRua', models.CharField(max_length=100)),
                ('clienteEnderecoNumero', models.CharField(max_length=10)),
                ('clienteEnderecoComplemento', models.CharField(blank=True, max_length=100)),
                ('clienteEnderecoCidade', models.CharField(max_length=50)),
                ('clienteEnderecoCep', models.CharField(max_length=10)),
                ('clienteTelefone', models.CharField(max_length=20)),
                ('clienteEmail', models.CharField(max_length=50)),
                ('clienteRepresentante', models.CharField(max_length=50)),
                ('clienteSegmento', models.CharField(max_length=50)),
                ('clienteEnderecoEstado', models.CharField(choices=[('', 'Escolher...'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=2)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcRegistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('funcCpf', models.CharField(max_length=14, unique=True)),
                ('funcNome', models.CharField(max_length=50)),
                ('funcEnderecoRua', models.CharField(max_length=100)),
                ('funcEnderecoNumero', models.CharField(max_length=10)),
                ('funcEnderecoComplemento', models.CharField(blank=True, max_length=100)),
                ('funcEnderecoCidade', models.CharField(max_length=50)),
                ('funcEnderecoCep', models.CharField(max_length=10)),
                ('funcTelefone', models.CharField(max_length=20)),
                ('funcEmail', models.CharField(max_length=50)),
                ('funcSenha', models.CharField(max_length=20)),
                ('funcFuncao', models.CharField(max_length=50)),
                ('funcDpto', models.CharField(max_length=50)),
                ('funcCnh', models.IntegerField(unique=True)),
                ('funcTipoCadastro', models.CharField(choices=[('', 'Escolher...'), ('Funcionario', 'Funcionario'), ('Administrador', 'Administrador')], default='', max_length=15)),
                ('funcEnderecoEstado', models.CharField(choices=[('', 'Escolher...'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=2)),
            ],
            options={
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('osNumero', models.BigAutoField(primary_key=True, serialize=False)),
                ('osDataAbertura', models.DateField(auto_now=True)),
                ('osDescricao', models.CharField(max_length=200)),
                ('osObservacao', models.CharField(blank=True, max_length=200)),
                ('osOutros', models.CharField(blank=True, max_length=100)),
                ('osTipoServico', models.CharField(choices=[('', 'Escolher...'), ('01', 'Manutenção'), ('02', 'Manutenção Preventiva'), ('03', 'Manutenção Corretiva'), ('04', 'Manutenção Preditiva'), ('05', 'Vistoria Técnica'), ('06', 'Limpeza'), ('07', 'Limpeza Ar-condicionado'), ('08', 'Treinamento'), ('09', 'Outros')], default='', max_length=100)),
                ('osClienteRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.cliente')),
                ('osFuncRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.funcionario')),
            ],
            options={
                'db_table': 'OrdemDeServico',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('veicRegistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('veicPlaca', models.CharField(max_length=7, unique=True)),
                ('veicModelo', models.CharField(max_length=50)),
                ('veicFabricante', models.CharField(max_length=50)),
                ('veicCor', models.CharField(max_length=20)),
                ('veicRenavam', models.IntegerField(unique=True)),
                ('veicAno', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), easyreport_web.models.max_value_current_year])),
            ],
            options={
                'db_table': 'Veiculo',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDeServico',
            fields=[
                ('relatorioNumero', models.BigAutoField(primary_key=True, serialize=False)),
                ('relatorioDescricao', models.CharField(max_length=200)),
                ('relatorioContatoCliente', models.CharField(max_length=50)),
                ('relatorioSetorClicente', models.CharField(max_length=50)),
                ('relatorioData', models.DateField(auto_now=True)),
                ('relatorioObservacao', models.CharField(blank=True, max_length=200)),
                ('relatorioFoto', models.FileField(blank=True, null=True, upload_to='')),
                ('relatorioComentarioCliente', models.CharField(blank=True, max_length=200)),
                ('relatorioOutros', models.CharField(blank=True, max_length=100)),
                ('relatorioTipoServico', models.CharField(choices=[('', 'Escolher...'), ('01', 'Manutenção'), ('02', 'Manutenção Preventiva'), ('03', 'Manutenção Corretiva'), ('04', 'Manutenção Preditiva'), ('05', 'Vistoria Técnica'), ('06', 'Limpeza'), ('07', 'Limpeza Ar-condicionado'), ('08', 'Treinamento'), ('09', 'Outros')], default='', max_length=100)),
                ('relatorioClienteRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.cliente')),
                ('relatorioFuncRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.funcionario')),
                ('relatorioOsNumero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.ordemdeservico')),
            ],
            options={
                'db_table': 'RelatorioDeServico',
            },
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='osVeicRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport_web.veiculo'),
        ),
    ]
