# Generated by Django 4.0.5 on 2022-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcCnh',
            field=models.BigIntegerField(unique=True),
        ),
    ]
