# Generated by Django 4.0.5 on 2022-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport_web', '0002_alter_funcionario_funccnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='veicPlaca',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='veicRenavam',
            field=models.BigIntegerField(unique=True),
        ),
    ]
