# Generated by Django 4.0.5 on 2022-06-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport_web', '0003_alter_veiculo_veicplaca_alter_veiculo_veicrenavam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clienteEnderecoComplemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcEnderecoComplemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='osObservacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='osOutros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeservico',
            name='relatorioComentarioCliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeservico',
            name='relatorioObservacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeservico',
            name='relatorioOutros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
