# Generated by Django 4.0.5 on 2022-06-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport_web', '0004_alter_cliente_clienteenderecocomplemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodeservico',
            name='relatorioEstado',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
